### ISSUE TITLE
dbshear missing module

### ISSUE THREAD

**Issue by tluckie13** [antelopeusersgroup/antelope_contrib#129]
After updating a clean install of Antelope 5.10 and rebuilding the contrib source tree from this master branch, the module `ztools.shear.dbshear` appears to be missing when trying to call the program `dbshear`. The output I receive is:
```
$ dbshear
Traceback (most recent call last):
  File "/opt/antelope/5.10/contrib/bin/dbshear", line 44, in <module>
    from ztools.shear.pick import shear_pick
  File "/opt/antelope/5.10/data/python/ztools/shear/pick.py", line 1, in <module>
    import ztools.shear.dbshear as algorithm
ModuleNotFoundError: No module named 'ztools.shear.dbshear'
```
Has this module been moved or renamed? 

Thanks

**Comment by tluckie13** [comment]
Workaround provided by Malcolm White:

>For some reason, the make tools no longer compile and install the missing module. The solution is to download the source >code and manually install the offending libraries by executing

```
$> cd ~/src/antelope_contrib/data/python/ztools/src/shear
$> make
$> sudo make install
```

>If the sudo make install command fails to deposit the library (as I have seen it do in the past), one can do it manually:

```
sh$> sudo mkdir -p /opt/antelope/5.9/data/python/ztools/shear
sh$> sudo mv dbshear.so __init__.py pick.py /opt/antelope/5.9/data/python/ztools/shear
```
